<FORM method="POST" action="<?php echo BASE . 'estoque/lista/';  ?>" enctype="multipart/form-data">
  <?php echo (isset($this->alert) ? $this->alert : '')?>
  <html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Major 23</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="<?php echo BASE. 'estoque;' ?>">
      </a>
    </nav>
    <br>
    <div class="container-fluid">
      <ul class="nav nav-pills nav-fill">
        <li class="nav-item">
          <a class="nav-link active" href="<?php echo BASE. 'estoque'; ?>" style="background-color: black">Estoque</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo BASE. 'comanda/menu/' ?>" style="color: black">Comandas</a>
        </li>
      </ul>
      <div class="text-center">
        <br>
        <br>
        <h1 class="h3 mb-2 font-weight-normal" >Estoque</h1>
        <br>
        <br>
          <a class="nav-link active" href="<?php echo BASE. 'estoque/adiciona'; ?>"><button type="button" class="btn btn-dark">Adicionar Item</button></a>
        <br>
        <br>
        <label for="cardapio">Tipo:</label>
        <select name="tipo" id="cardapio" required="true">
          <option value="Pratos">Pratos</option>
          <option value="Lanches">Lanches</option>
          <option value="Bebidas">Bebidas</option>
          <option value="Sobremesa">Sobremesa</option>
          <option value="Outros">Outros</option>
        </select>
        <button type="submit" class="btn btn-dark">Editar Item</button>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
  </html>