<!doctype html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo $view_title; ?></title>
  <link rel="shortcut icon" href="<?php echo IMG; ?>agp.ico" type="image/x-icon">
  <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="<?php echo CSS; ?>cor.css" type="text/css">
  <script src="<?php echo BOWER; ?>bootstrap/js/jquery.js"></script>
  <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap.min.js"></script>
  <?php 
  echo $add_css;
  echo $add_js;
  ?>
</head>

