<?php 
$total = 0;
foreach ($view_itens as $i) {
  $total = (Product::find($i->products_id)->preco * $i->qtd) + $total;
} ?>
<html lang="pt">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Major 23</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="<?php echo BASE.'comanda/lista'; ?>"><button type="button" class="btn btn-dark">Voltar</button></a>
  </nav>
  <br>
  <div class="container-fluid">
    <div class="text-center">
      <br>
      <br>

      <h1 class="h3 mb-2 font-weight-normal">Comanda <?php echo $view_pedido->id; ?></h1>
      <br>
    </div>
    <b>Mesa:</b> <?php echo  (!empty($view_pedido->mesa) ? $view_pedido->mesa : '-'); ?> &nbsp <b>Viagem:</b> <?php echo ($view_pedido->viagem == 1 ? 'Sim': 'Não'); ?>
    <br>
    <b>Preço Total:</b> R$ <?php echo $total; ?> &nbsp <b>Status:</b> <?php echo $view_pedido->status; ?>
    <br>
    <b>Observações:</b> <?php echo (!empty($view_pedido->observacao) ? $view_pedido->observacao : '-');; ?>
    <br>
    <br>
    <div class="text-center">
      <h1 class="h5 mb-2 font-weight-normal">Itens</h1>
    </div>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Tipo:</th>
          <th scope="col">Produto:</th>
          <th scope="col">Quantidade:</th>
          <th scope="col">Preço:</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($view_itens as $i) {
          $produto = Product::find($i->products_id);
          ?>
          <tr>
            <th scope="row"><?php echo $produto->tipo; ?></th>
            <td><?php echo $produto->nome; ?></td>
            <td><?php echo $i->qtd; ?></td>
            <td>R$ <?php echo $produto->preco * $i->qtd; ?></td>
          </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
</body>
</html>