<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Major 23</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="<?php echo BASE.'comanda/ativa';?>"><button type="button" class="btn btn-dark">Voltar</button></a>
    <?php
    $teste = 0;
    $itens = RequestItem::find_all_by_requests_id($view_id);
    foreach ($itens as $i) {
      $teste = (Product::find($i->products_id)->preco * $i->qtd) + $teste;
    }
    ?>
    <div class="justify-content-end">Preço total: R$ <?php echo $teste; ?></div>
  </nav>
  <br>
  <div class="container-fluid">
    <div class="text-center">
      <br>
      <br>
      <h1 class="h3 mb-2 font-weight-normal">Fechar Comandas</h1>
      <br>
      <br>
      <div class="text-center">
        <a href="#"><button type="button" class="btn btn-dark" data-toggle="modal" data-target="#Pagar">Pagar comanda</button></a>
        <br>
        <br>
        <a href="#"><button type="button" class="btn btn-dark" data-toggle="modal" data-target="#Cancelar">Cancelar comanda</button></a>
      </div>
    </div>
  </div>
  <!-- Modal de Mensagem Cancelamento -->
  <div class="modal fade" id="Cancelar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Cancelamento</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Deseja cancelar comanda?
        </div>
        <div class="modal-footer">
          <a href=""><button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button></a>
          <a href="<?php echo BASE.'comanda/cancelar/'.$view_id; ?>"><button type="button" class="btn btn-dark">Sim</button></a>
        </div>
      </div>
    </div>
  </div>
  <!-- Modal de Mensagem Pagamento -->
  <div class="modal fade" id="Pagar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Pagamento</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Deseja pagar comanda?
        </div>
        <div class="modal-footer">
          <a href=""><button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button></a>
          <a href="<?php echo BASE.'comanda/pagar/'. $view_id; ?>"><button type="button" class="btn btn-dark">Sim</button></a>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
</body>
</html>