<aside class="container">
    <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-body">
              <center><p>
                  <div class="row">
                      <br>
                  </div>
                  <div class="row">
                      <br>
                  </div>
                  <div class="row">
                      <br>
                  </div>
                  <div class="row">
                      <br>
                  </div>
                  <div class="row">
                      <br>
                  </div>
                  <div class="row">
                      <br>
                  </div>
                  <div class="row">
                      <br>
                      <div class="row">
                          <br>
                          <font size="8">
                             <!-- Mensagem -->
                             <b>OPS... </b>
                         </font><font size="6">
                         <!-- Mensagem -->
                         <b>P&aacute;gina N&atilde;o Encontrada.  &macr;\_(ツ)_/&macr;</b>
                     </font>
                     <div class="row">
                      <br>
                      <div class="row">
                          <br>
                          <div class="row">
                              <br>
                          </div>
                          <div class="row">
                              <br>
                          </div>
                          <div class="row">
                              <br>
                          </div>
                          <div class="row">
                              <br>
                          </div>
                          <div class="row">
                              <br>
                          </div>
                          <div class="row">
                              <br>
                          </div>
                      </p></center>
                  </div>
              </div>
          </div>
      </aside>
